exception_count = 0

def print_exception(exeption):
    print('----------------------------------------------------------------------------------')
    print(exeption)
    exception_count=+1
    print('----------------------------------------------------------------------------------')
    input("Print enter to continue")