def print_exception(exeption):
    print('----------------------------------------------------------------------------------')
    print(exeption)
    print('----------------------------------------------------------------------------------')
    input("Print enter to continue")